import { RewardType } from "../../../types/common/main";
import { reward1Chances, reward3Chances, reward4Chances } from "../chances";
import { ITEMQUALITY, ITEMTYPE } from "../enums";

const commonRewards: RewardType[] = [
    {
        name: "Crown Lethal Poison (25)",
        cardImage: '/images/crates/genericCommon/Crown_Lethal_Poison.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.normal,
        reward3Chance:reward3Chances.common.poison1,
        reward4Chance: reward4Chances.common.pot1,
    },
    {
        name: "Crown Mimic Stone",
        cardImage: '/images/crates/genericCommon/Crown_Mimic_Stone.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.special,
    },
    {
        name: "Crown Tri-Restoration Potion (5)",
        cardImage: '/images/crates/genericCommon/Crown_Tri-Restoration_Potion.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.normal,
        reward3Chance:reward3Chances.common.potion,
        reward4Chance: reward4Chances.common.tripot,
    },
    {
        name: "Gold Coast Debilitating Poison (50)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Debilitating_Poison.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.potion,
        reward4Chance: reward4Chances.common.pot2,
    },
    {
        name: "Gold Coast Draining Poison (50)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Draining_Poison.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.potion,
        reward4Chance: reward4Chances.common.pot2,
    },
    {
        name: "Gold Coast Enfeebling Poison (50)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Enfeebling_Poison.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.potion,
        reward4Chance: reward4Chances.common.pot2,
    },
    {
        name: "Gold Coast Spellcaster Elixir (10)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Spellcaster_Elixir.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.special,
        reward4Chance: reward4Chances.common.pot1,
    },
    {
        name: "Gold Coast Survivor Elixir (10)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Survivor_Elixir.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.special,
        reward4Chance: reward4Chances.common.pot1,
    },
    {
        name: "Gold Coast Swift Survivor Elixir (10)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Swift_Survivor_Elixir.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.special,
        reward4Chance: reward4Chances.common.pot1,
    }
    ,
    {
        name: "Gold Coast Trapping Poison (50)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Trapping_Poison.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.potion,
        reward4Chance: reward4Chances.common.pot1,
    },
    {
        name: "Gold Coast Warrior Elixir (10)",
        cardImage: '/images/crates/genericCommon/Gold_Coast_Warrior_Elixir.png',
        quality: ITEMQUALITY.common,
        type: ITEMTYPE.consumable,
        gems: 1,
        reward1Chance:reward1Chances.common.poison,
        reward3Chance:reward3Chances.common.special,
        reward4Chance: reward4Chances.common.pot1,
    },
]

export default commonRewards